### ISSUE TITLE
Question about the implementation of 'emit.Int'

### ISSUE THREAD

**Issue by hactrox** [nspcc-dev/neo-go#1071]
https://github.com/nspcc-dev/neo-go/blob/93b00119884a2b01f338d7e73e68f4b2788e5e63/pkg/vm/emit/emit.go#L63

If I want to emit 65535, the desired result should be `0x02`(opcode) + `0xffff00`(byte array) = `02ffff00`. 
The variable 'buf' at line 59 is correct, but after the 'padRight' function call, an extra 0x00 is appended(because the 'buf' array inside this function is expanded from 3 to 4), the result becomes `0x02` + `0xffff0000` = `02ffff0000`.

The following c# code can prove it:
```c#
Console.WriteLine(ByteArrayToString(new BigInteger(65535).ToByteArray()));
// Output: ffff00
```

**Comment by roman-khimov** [comment]
IIRC, C# code doesn't use new NeoVM 3 PUSHINTX opcodes for integers, relying instead on PUSHDATAX, that's why it uses standard `BigInteger` to `ByteArray` conversion routines.

neo-go instead uses appropriate PUSHINTX which for your particular value of 65535 should be PUSHINT32 (opcode 0x02) and this instruction has to have a full 4-byte parameter, that's why the value is being expanded. I think this behavior is correct, if you're to run the code produced in a VM it should work.

```
NEO-GO-VM > loadhex 02ffff00
READY: loaded 4 instructions
NEO-GO-VM 0 > run
Error: error encountered at instruction 0 (PUSHINT32): failed to read instruction parameter
NEO-GO-VM > loadhex 02ffff0000
READY: loaded 5 instructions
NEO-GO-VM 0 > run
[
    {
        "type": "Integer",
        "value": "65535"
    }
] 
```

**Comment by hactrox** [comment]
@roman-khimov Thanks for your explanation.
