### ISSUE TITLE
Test `CheckWitness` syscall

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#1366]
1. It should be able to process non-tx types
https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.Runtime.cs#L140
2. Cover everything with tests.

**Comment by roman-khimov** [comment]
1) I don't think it really needs to. If it's not a transaction, it's either a block or consensus payload. Consensus payloads are only verified and that's the simplest verification possible. Blocks are a bit more complex because of `OnPersist`, but even then `CheckWitness` is never used by these functions. So theoretically it might be a problem, but practically I doubt so.
