### ISSUE TITLE
VM : Add Map and Struct Types

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#167]
For map I believe it is:
Map[StackItem] -> StackItem

For struct:

-- I believe a struct is the same as an array, but with different behavioural qualities.

**Comment by dauTT** [comment]
FYI, I am working on this.

**Comment by dauTT** [comment]
@decentralisedkev ,

the naive way to implement the `StackItem Map` is as as follow:
```go
type Map struct {
	*abstractItem
	val map[Item]Item
}
```

However this struct is not going to work because `Item` is an interface and doing lookup on an interface is not possible and it seems to me that we can't implement custom `equality` to lookup the key in `map[Item]Item`

So my proposal is to implement StackItem Map as follow:

```go
type Map struct {
	*abstractItem
	val map[String]Item  // String represent the Hash of the key Item.
}
```
If we follow this route, we would need to extend the `Item` interface and `abstractItem` with a Hash() method and all the concrete Items (Boolean, Array, ..) must override this method. 
WDYT?

**Comment by decentralisedkev** [comment]
SGTM. I could not find many tests on `Map`, so let's just implement it as best as possible, then refactor, if necessary when implementing the opcodes.

For ideas, you can also look at the opcodes under array

**Comment by roman-khimov** [comment]
Master has some support for structs, but doesn't know anything about maps. Dev has no support for both of them.
