### ISSUE TITLE
rpc: ensure that (*Client).AddNetworkFee can properly calculate network fee for main Notary transaction

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#1799]
Consider the following incomplete Notary main transaction signers:
1. Deployed contract with `verify` method
2. Multisig signer
3. Notary contract

We need to ensure that `(*Client).AddNetworkFee` is able to calculate the network fee for signers 1 and 2 properly.

The resulting transaction network fee (which is `AddNetworkFee(...) + CalculateNotaryFee(...)`)  should be enough to complete the transaction and to send it to the chain.

**Comment by roman-khimov** [comment]
The problem is that deployed contract can demand any kind of invocation script. It can be empty script, it can have some signature inside, it can have multiple signatures inside, it can have hash/hashes, whatever. Invocation script obviously affects size/GAS spent on verification, so it's impossible to solve in generic way.

**Comment by AnnaShaleva** [comment]
@roman-khimov, I think that at least we can solve this problem for empty invocations scripts (which is what our `AddNetworkFee` does). And this solves the problem with extra GAS addition for NeoFS proxy-contract witnesses verification (see [the comment L21-23](https://github.com/nspcc-dev/neofs-node/pull/404/files#diff-639db437ca2578db46c9e8cbf18f9aa01f8ca5aee30e0fa7e70ba0354822d7b3R21-R23))

But with the changes from #1825 it's not hard to extend the functionality of the `AddNeworkFee` to work with non-empty invocation scripts.
