### ISSUE TITLE
getnep5balances do not return the full list of nep5 tokens

### ISSUE THREAD

**Issue by adrienmo** [nspcc-dev/neo-go#1833]
`getnep5balances` do not return the full list of nep5 tokens while direct call to the smart contract works.

FLM token: `4d9eab13620fe3569ba3b0e56e2877739e4145e3`
address: `AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM`
script hash: `4bdfdd2e0af2e08eaae3fcb9391a29db49d0735e`

```
curl -k -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM"], "id": 1}' https://rpc3.go.nspcc.ru:10331

{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "balance": [
      {
        "asset_hash": "3a4acd3647086e7c44398aac0349802e6a171129",
        "amount": "64968000",
        "last_updated_block": 6887010
      },
      {
        "asset_hash": "132947096727c84c7f9e076c90f08fec3bc17f18",
        "amount": "1152667658330",
        "last_updated_block": 4817532
      },
      {
        "asset_hash": "a87cc2a513f5d8b4a42432343687c2127c60bc3f",
        "amount": "400000000000",
        "last_updated_block": 4817496
      },
      {
        "asset_hash": "d0394dd3ee1cdd8ae18665a22c7ca3af52aafd7a",
        "amount": "10000000",
        "last_updated_block": 4817513
      },
      {
        "asset_hash": "fc732edee1efdf968c23c20a9628eaa5a6ccb934",
        "amount": "230",
        "last_updated_block": 4817530
      }
    ],
    "address": "AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM"
  }
}
```

```
curl -k -X POST -d '{"jsonrpc": "2.0", "method": "invokefunction", "params": ["4d9eab13620fe3569ba3b0e56e2877739e4145e3", "balanceOf", [{"type": "Hash160", "value": "4bdfdd2e0af2e08eaae3fcb9391a29db49d0735e"}]], "id": 1}' https://rpc3.go.nspcc.ru:10331

{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "state": "HALT",
    "gas_consumed": "0.263",
    "script": "145e73d049db291a39b9fce3aa8ee0f20a2edddf4b51c10962616c616e63654f6667e345419e7377286ee5b0a39b56e30f6213ab9e4d",
    "stack": [
      {
        "type": "ByteArray",
        "value": "8ace7a25"
      }
    ]
  }
}
```

**Comment by adrienmo** [comment]
Same for EFX token:

EFX token: `ACBC532904B6B51B5EA6D19B803D78AF70E7E6F9`
Address: `AL3wPVmokZPGheobABA8YKLkSmbuP97pnP`
script hash: `3417582fd64a562a9aa32c4f875bdd2a1a48ea2e`


```
curl -k -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AL3wPVmokZPGheobABA8YKLkSmbuP97pnP"], "id": 1}' https://rpc2.go.nspcc.ru:10331
{"id":1,"jsonrpc":"2.0","result":{"balance":[{"asset_hash":"3a4acd3647086e7c44398aac0349802e6a171129","amount":"12495999997","last_updated_block":5737553},{"asset_hash":"a87cc2a513f5d8b4a42432343687c2127c60bc3f","amount":"200000000000","last_updated_block":5124166}],"address":"AL3wPVmokZPGheobABA8YKLkSmbuP97pnP"}}
```

```
curl -k -X POST -d '{"jsonrpc": "2.0", "method": "invokefunction", "params": ["ACBC532904B6B51B5EA6D19B803D78AF70E7E6F9", "balanceOf", [{"type": "Hash160", "value": "3417582fd64a562a9aa32c4f875bdd2a1a48ea2e"}]], "id": 1}' https://rpc2.go.nspcc.ru:10331
{"id":1,"jsonrpc":"2.0","result":{"state":"HALT","gas_consumed":"0.233","script":"142eea481a2add5b874f2ca39a2a564ad62f58173451c10962616c616e63654f6667f9e6e770af783d809bd1a65e1bb5b6042953bcac","stack":[{"type":"ByteArray","value":"00a0db215d"}]}}
```

**Comment by adrienmo** [comment]
> `getnep5balances` do not return the full list of nep5 tokens while direct call to the smart contract works.
> 
> FLM token: `4d9eab13620fe3569ba3b0e56e2877739e4145e3`
> address: `AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM`
> script hash: `4bdfdd2e0af2e08eaae3fcb9391a29db49d0735e`
> 
> ```
> curl -k -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM"], "id": 1}' https://rpc3.go.nspcc.ru:10331
> 
> {
>   "id": 1,
>   "jsonrpc": "2.0",
>   "result": {
>     "balance": [
>       {
>         "asset_hash": "3a4acd3647086e7c44398aac0349802e6a171129",
>         "amount": "64968000",
>         "last_updated_block": 6887010
>       },
>       {
>         "asset_hash": "132947096727c84c7f9e076c90f08fec3bc17f18",
>         "amount": "1152667658330",
>         "last_updated_block": 4817532
>       },
>       {
>         "asset_hash": "a87cc2a513f5d8b4a42432343687c2127c60bc3f",
>         "amount": "400000000000",
>         "last_updated_block": 4817496
>       },
>       {
>         "asset_hash": "d0394dd3ee1cdd8ae18665a22c7ca3af52aafd7a",
>         "amount": "10000000",
>         "last_updated_block": 4817513
>       },
>       {
>         "asset_hash": "fc732edee1efdf968c23c20a9628eaa5a6ccb934",
>         "amount": "230",
>         "last_updated_block": 4817530
>       }
>     ],
>     "address": "AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM"
>   }
> }
> ```
> 
> ```
> curl -k -X POST -d '{"jsonrpc": "2.0", "method": "invokefunction", "params": ["4d9eab13620fe3569ba3b0e56e2877739e4145e3", "balanceOf", [{"type": "Hash160", "value": "4bdfdd2e0af2e08eaae3fcb9391a29db49d0735e"}]], "id": 1}' https://rpc3.go.nspcc.ru:10331
> 
> {
>   "id": 1,
>   "jsonrpc": "2.0",
>   "result": {
>     "state": "HALT",
>     "gas_consumed": "0.263",
>     "script": "145e73d049db291a39b9fce3aa8ee0f20a2edddf4b51c10962616c616e63654f6667e345419e7377286ee5b0a39b56e30f6213ab9e4d",
>     "stack": [
>       {
>         "type": "ByteArray",
>         "value": "8ace7a25"
>       }
>     ]
>   }
> }
> ```

C# version seems to work:

```
curl -k -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM"], "id": 1}' http://seed2.ngd.network:10332

{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "balance": [
      {
        "asset_hash": "132947096727c84c7f9e076c90f08fec3bc17f18",
        "amount": "1152667658330",
        "last_updated_block": 4817532
      },
      {
        "asset_hash": "3a4acd3647086e7c44398aac0349802e6a171129",
        "amount": "64968000",
        "last_updated_block": 6887010
      },
      {
        "asset_hash": "fc732edee1efdf968c23c20a9628eaa5a6ccb934",
        "amount": "230",
        "last_updated_block": 4817530
      },
      {
        "asset_hash": "a87cc2a513f5d8b4a42432343687c2127c60bc3f",
        "amount": "400000000000",
        "last_updated_block": 4817496
      },
      {
        "asset_hash": "f735eb717f2f31dfc8d12d9df379da9b198b2045",
        "amount": "5496468",
        "last_updated_block": 4817528
      },
      {
        "asset_hash": "d0394dd3ee1cdd8ae18665a22c7ca3af52aafd7a",
        "amount": "10000000",
        "last_updated_block": 4817513
      },
      {
        "asset_hash": "de7be47c4c93f1483a0a3fff556a885a68413d97",
        "amount": "1",
        "last_updated_block": 4817526
      },
      {
        "asset_hash": "f46719e2d16bf50cddcef9d4bbfece901f73cbb6",
        "amount": "100000000",
        "last_updated_block": 7053774
      },
      {
        "asset_hash": "2328008e6f6c7bd157a342e789389eb034d9cbc4",
        "amount": "1",
        "last_updated_block": 4817519
      },
      {
        "asset_hash": "4d9eab13620fe3569ba3b0e56e2877739e4145e3",
        "amount": "628805258",
        "last_updated_block": 7053774
      }
    ],
    "address": "AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM"
  }
}
```

**Comment by roman-khimov** [comment]
If you're to grab full transfer log for this address (`"method": "getnep5transfers", "params": ["AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM", 0, 2600094189]`) and take transfers of `4d9eab13620fe3569ba3b0e56e2877739e4145e3` from it, the balance (received - sent) you'd get will be negative (as [suggested by neoscan](https://neoscan.io/address/AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM)). Which to me means that something is wrong with transfer notifications from this contract. I know how to fix balances, there is a known kludge for that, but I'd really like to understand why they need to be fixed and can we trust transfer notifications at all (each and every balance change is supposed to trigger `transfer` event and thus balance should be precisely trackable via these events).

**Comment by roman-khimov** [comment]
It can be tracked down to the first three FLM transactions for this address:
 * 6c3fbfa9d559a914030976122c0eb4ca665391bf0ce7c6011fb7e4d7da5f48c7 adds 12249000000 FLM (AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM receives them)
 * 7cfc595ef9c0e5b1d3d7f71ab15eb0576c66e5d78dc18f25005feb446ad7214f adds 13831000000 FLM more
 * and then 4540936e4d0039afb0bc28c87bb89ac64db6017e5d038fde53be17bcf4458491 transfers 45997520968 FLM from the address

So given 260.8 FLM balance we successfuly transferred 459.97520968 FLM from the address. Obviously the balance wasn't 260.8, but how did it change without notice (`transfer` event)?

**Comment by roman-khimov** [comment]
@adrienmo: do you know anything about AeazQGf3H3RVuKjFjU4aMPeixShVvbT41f address?

**Comment by roman-khimov** [comment]
Well, thanks to historical state data (stateroots, yay) we can get some picture of things happening here.

A note on instruments used first, though:
 * `getstateroot` requests to get verified state for a particular block, state at block X means state of the chain _after_ block X processing
 * `getproof` to request state proofs for given stateroot and contract/key pair, the request looks like this: `curl -d '{"jsonrpc": "2.0", "method": "getproof", "params": ["0x476ddbe1e17def109f2e7af722147f701bcdb69565617afc27a42d04df642feb", "4d9eab13620fe3569ba3b0e56e2877739e4145e3", "01015e73d049db291a39b9fce3aa8ee0f20a2edddf4b"], "id": 1}' $RPCNODE`, where `0x476ddbe1e17def109f2e7af722147f701bcdb69565617afc27a42d04df642feb` is a state root hash, `4d9eab13620fe3569ba3b0e56e2877739e4145e3` is an FLM contract hash and `01015e73d049db291a39b9fce3aa8ee0f20a2edddf4b` is a key we're interested in (`0101` prefix is used by FLM for balances and `5e73d049db291a39b9fce3aa8ee0f20a2edddf4b` is a script hash of `AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM` address (reverse of `4bdfdd2e0af2e08eaae3fcb9391a29db49d0735e`, thanks to #938)). It's output is a bit non-trivial to parse, but `success` tells us that there is a key in the DB and the value stored is at the end of the `proof`)
 * good old friend, `getapplicationlog` to get notifications emitted from transaction as is

So:
 * at block 6225786 (state root `0x476ddbe1e17def109f2e7af722147f701bcdb69565617afc27a42d04df642feb`) there is no balance stored for `AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM` in FLM contract
 * at block 6225787 (`0x1895500a986893c1a025c98a98a8cc79463f378ef2080b4877c86edfaafc5038`) it first appears with value of `b5aeb34002` which is `9675452085` or 96.75452085 FLM, but the only transaction involving AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM is `1ac16723d1356377e4519adaf3a3dc30032cda721e92c5743abfc8a6e4d2af3a` ([neoscan](https://neoscan.io/transaction/1ac16723d1356377e4519adaf3a3dc30032cda721e92c5743abfc8a6e4d2af3a), [neotube](https://neotube.io/transaction/0x1ac16723d1356377e4519adaf3a3dc30032cda721e92c5743abfc8a6e4d2af3a))
 * `1ac16723d1356377e4519adaf3a3dc30032cda721e92c5743abfc8a6e4d2af3a` application log contains this:
   ```
            "notifications" : [
               {
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteArray",
                           "value" : "7472616e73666572"
                        },
                        {
                           "type" : "ByteArray",
                           "value" : ""
                        },
                        {
                           "type" : "ByteArray",
                           "value" : "fa3bf4bb6123ab9646f3c7ed6ebd28b3478d4407"
                        },
                        {
                           "value" : "9675452085",
                           "type" : "Integer"
                        }
                     ]
                  },
                  "contract" : "0x4d9eab13620fe3569ba3b0e56e2877739e4145e3"
               }
            ],
   ```
   where we have notification from FLM contract about transfer of 96.75452085 FLMs to AeazQGf3H3RVuKjFjU4aMPeixShVvbT41f (and this is the way it's displayed by any blockchain explorer)
 * notice that the address is completely different, even though the amount is exactly what we're expecting to see
 * if we're to take a look at state data for AeazQGf3H3RVuKjFjU4aMPeixShVvbT41f (`0101fa3bf4bb6123ab9646f3c7ed6ebd28b3478d4407` key), it's the same `bc0fc5ac08733c1d131e19c0ee69c6af75fdac02488930a6432ccef86c5ebf56` leaf at 6225786 and 6225787 with value of `030400010100`: 0x03 leaf type, 0x04 bytes of data, 0x00 version, 0x0101 contract's data (length 1, value 1), 0x00 constant flag), so the balance of AeazQGf3H3RVuKjFjU4aMPeixShVvbT41f haven't changed at all
 * same thing happens with 0xfecf691c2bab9503c728ae7ce5335587b828b4c73e728a09e7e345f817f76c5c ([neotube](https://neotube.io/transaction/0xfecf691c2bab9503c728ae7ce5335587b828b4c73e728a09e7e345f817f76c5c), [neoscan](https://neoscan.io/transaction/FECF691C2BAB9503C728AE7CE5335587B828B4C73E728A09E7E345F817F76C5C)) at block 6228138, we have balance of 9675452085 at 6228137 for AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM and 12090216339 at 6228138, so the difference is exactly 2414764254 that were minted in this transaction (which again notifies about transfer to AeazQGf3H3RVuKjFjU4aMPeixShVvbT41f instead of AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM)
 * so our NEP-5 tracker thinks we have zero balance when 0x6c3fbfa9d559a914030976122c0eb4ca665391bf0ce7c6011fb7e4d7da5f48c7 happens, while in fact it's not; this transaction has proper `transfer` event with AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM as receiver
 * this balance mismatch causes all other problems
 * I have no idea what this `AeazQGf3H3RVuKjFjU4aMPeixShVvbT41f` address is (`07448d47b328bd6eedc7f34696ab2361bbf43bfa` or `fa3bf4bb6123ab9646f3c7ed6ebd28b3478d4407` hashes don't correspond to any deployed contract)

To me this behavior suggests that FLM token is broken and not NEP-5 conformant, it uses inappropriate `to` address for `transfer` events generated when minting FLM tokens. You can't rely on these events if you need to track FLM mints. Tracking AeazQGf3H3RVuKjFjU4aMPeixShVvbT41f can help, but I'm not sure it's reliable either.

And there is no real fix for it, even if we're to implement the kludge mentioned above (and get real balance from the contract on every transfer), the event stream is broken and up until 6233750 (when 0x6c3fbfa9d559a914030976122c0eb4ca665391bf0ce7c6011fb7e4d7da5f48c7 comes in) both neo-go and C# trackers would give you no FLM balance data for AQPHuQHTC7opfyeGSLQ1y76dUwFqZiNHnM, just because there are no NEP-5 events for this address from FLM contract.

For example, take a very recent 0x6529a54a60befbcfdddcf826b4c85fe79a48efec0ab84145259ab386a70b9dac transaction and check for AbeUDM63h1i8PdHzrDrYRmKvPv5mQz8JZY balance:
```
$ curl -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AbeUDM63h1i8PdHzrDrYRmKvPv5mQz8JZY"], "id": 1}' http://seed5.ngd.network:10332 | json_pp 
{
   "result" : {
      "address" : "AbeUDM63h1i8PdHzrDrYRmKvPv5mQz8JZY",
      "balance" : [
         {
            "amount" : "6060364761",
            "last_updated_block" : 6948412,
            "asset_hash" : "f46719e2d16bf50cddcef9d4bbfece901f73cbb6"
         }
      ]
   },
   "id" : 1,
   "jsonrpc" : "2.0"
}
$ curl -k -X POST -d '{"jsonrpc": "2.0", "method": "invokefunction", "params": ["4d9eab13620fe3569ba3b0e56e2877739e4145e3", "balanceOf", [{"type": "Hash160", "value": "ce5949bd34ddd849235d91a148249de3e20afcd9"}]], "id": 1}' http://seed5.ngd.network:10332 | json_pp
{
   "id" : 1,
   "result" : {
      "state" : "HALT",
      "script" : "14d9fc0ae2e39d2448a1915d2349d8dd34bd4959ce51c10962616c616e63654f6667e345419e7377286ee5b0a39b56e30f6213ab9e4d",
      "stack" : [
         {
            "value" : "59dc6cee1b",
            "type" : "ByteArray"
         }
      ],
      "gas_consumed" : "0.263"
   },
   "jsonrpc" : "2.0"
}
```
and nep5balances data won't be updated until some (non-mint) transfer occurs, you can check it yourself by minting FLM and comparing balances.

**Comment by adrienmo** [comment]
@roman-khimov Thanks for your in-depth analysis.

neo-go and neo-c# have diverging response for the same arguments. I guess neo c# came up with some hacky methods to solve this. The question now is the following: will neo-go try to replicate the behaviour of neo-c# to keep consistency between the node?

**Comment by roman-khimov** [comment]
We can do this, but as mentioned above, you still won't get correct values in some cases. Just because we're tracking NEP-5 tokens and FLM is not a proper NEP-5 token. So I'm not sure it's worth doing that, the data from nep5balances/nep5transfers just can't be reliable for FLM irrespective of node/tracker implementation.

**Comment by adrienmo** [comment]
It seems it is the case for many tokens. Another example with GUARD:

```
curl -k -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AR3kEFg7AazEzcY1UM877dhkcb2Sv3dbki"], "id": 1}' https://rpc3.go.nspcc.ru:10331


curl  -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AR3kEFg7AazEzcY1UM877dhkcb2Sv3dbki"], "id": 1}' https://mainnet3.neo2.coz.io:443
```

**Comment by roman-khimov** [comment]
I'll take a look at it.

**Comment by roman-khimov** [comment]
IIRC the path was a bit longer than I've expected here, leading to some exchange address where it was hard to trace the exact sequence of events. Anyway, the core problem would be the same here and at the same time we have whole new N3 node that works in a bit different way for NEP-17 tracking, so I doubt this issue would be relevant for it and we know why it happens in Legacy (broken tokens).
