### ISSUE TITLE
Oracle JSONPath filter result differs from result of testnet oracles

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#1903]
neo-go version 0.94.1

I used JSONPath filter `$..item[?(@.id==1)].price` in oracle call of the JSON object stored in NeoFS:

```json
{ "store": {
    "item": [
      { "id": 1,
        "category": "clothing",
        "title": "Aloha Shirt",
        "price": 700
      },
      { "id": 2,
        "category": "clothing",
        "title": "Pearl Tee",
        "price": 400
      },
      { "id": 3,
        "category": "headgear",
        "title": "Fugu Bell Hat",
        "price": 1700
      },
      { "id": 4,
        "category": "headgear",
        "title": "Splash Goggles",
        "price": 2800
      },
      { "id": 5,
        "category": "shoes",
        "title": "Cherry Kicks",
        "price": 2400
      },
      { "id": 6,
        "category": "shoes",
        "title": "Red Hi-Tops",
        "price": 1800
      }
    ]
  }
}
```

In neofs-dev-env environment, single neo-go oracle node returned `[[700]]` string. But oracle nodes in N3 testnet returned `[700]` string.

**Comment by roman-khimov** [comment]
Array-wrapping was added intentionally by @fyrchik, but I'm not sure which cases needed it.

**Comment by fyrchik** [comment]
Consider `$..store.item[0]` vs. `store.item[0]`.
JSON path (e.g. here https://jsonpath.com/, I believe C# node behaves the same) should always result in array, however our library returns array for the former and an object for the latter. The wrapping was added to support the second case, because it was present in C# unit-tests. Another library I tried didn't support `store.item[0]` case at all.

One could think we can simply check leading `$`, but if we consider `$.store.item[0]` (one dot after `$`) it results to an object, though an array is expected.

I think restricting set of allowed filters is the way to go.
