### ISSUE TITLE
VM: Add Interopability tests with neo-vm

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#196]

**Comment by roman-khimov** [comment]
#358 specifically left out `_pkg.dev/vm/csharp-interop-test/` to serve as some starting point for this work.

**Comment by fyrchik** [comment]
I have started working on this in the separate branch `feature/neoUT`. I am planning to create issues fix bugs. When all bugs will be fixed and json unit-tests will move to a separate repo, I will create PR on merging this branch into master.

**Comment by fyrchik** [comment]
It seems like most of the test which don't use `NEWMAP`, `SYSCALL` or `TAILCALL` and which do not involve limit checking (see #373 ) work.

Here is a list of bugs which need to be fixed in master and for which there are no related issues:
- [ ] fail if `NIP`, `(X)DROP`, `ROT` or `EQUAL` have not enough arguments.
- [ ] fail if `XTUCK` argument is 0
- [ ] `PICKITEM` should accept bytearrays
- [ ] `NEWARRAY`/`NEWSTRUCT` should create array of `BoolItem{false}` items instead of `nil`s
- [ ] `REMOVE` should return value of the same type as the argument (do not perform `Struct -> Array` conversion)
- [ ] `PUSH0` should push empty byte array (it is converted when 0 is needed)
- [ ] if an item to be `APPEND`ed is a struct, it should be cloned. NOTE: it is about appended item, not an array.
- [ ] array should be compared on equality by reference
- [ ] `NEWARRAY` can accept `[]byte` operand. Common usecase: `PUSH0, NEWARRAY`
- [ ] `SIZE` can accept any argument castable to `ByteArray`
- [ ] `SHL`/`SHR` do not change type of the operand if shift is by 0 (if applied to bytearray, leave bytearray as it is).

There is a very little work to be done in every task so it will probably be better to handle them in 1 PR with several commits. What do you think? @roman-khimov

**Comment by roman-khimov** [comment]
> There is a very little work to be done in every task so it will probably be better to handle them in 1 PR with several commits. 

Works fine for me.
