### ISSUE TITLE
single binary for different platforms

### ISSUE THREAD

**Issue by gsmachado** [nspcc-dev/neo-go#2008]
Hello neo-go'ers,

The community **urges** (😅 ) for the following: as a developer aiming to run a Neo N3 node (even for private net), I would like just to download a single damn binary file, execute it, and that's it. It runs.

No dependencies. No external tools. No building from sources for my OS/platform. No complexity. Just download it, `chmod u+x neo-go`, `./neo-go`, and that's it.

Given that I'm also a Golang dev, I know that this is very much doable with Go. *And this is a huge advantage compared to C#*. In the Java/Kotlin world, static fat binaries are also possible to be achieved, but we don't have a Neo N3 node reference implementation in [neow3j](https://github.com/neow3j/neow3j).

IMHO, it's just a matter of 1) checking compatibility of dependencies targeting different GOARCH/GOOS, and 2) adjusting the CI-CD to produce such artifacts, automatically, for each release.

My suggestions for `GOOS` and `GOARCH`, in priority order:

1. `GOOS=linux`,  `GOARCH=amd64` (it's already being shipped, I know)
2. `GOOS=darwin`,  `GOARCH=amd64`
3. `GOOS=windows`,  `GOARCH=amd64`
4. `GOOS=linux`,  `GOARCH=arm`
5. `GOOS=linux`,  `GOARCH=arm64`

For `GOARCH=arm` and `GOARCH=arm64`, it would be nice to also set the `GOARM` var. As an example, the flags below are compatible with a Raspberry Pi with armv7 minimum compatibility:

`CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ GOARCH=arm GOOS=linux GOARM=7 CGO_ENABLED=1`

**Comment by roman-khimov** [comment]
It's not hard to build this set of binaries, it's much harder to ensure they work. NeoGo is `CGO_ENABLED=0` btw, which probably increases chances to succeed, but at the same time we're all linux/amd64 here, so who is to check whether any of these OS/ARCH combinations works? And who is to fix any potential bugs there?

It'd be nice to see actual (bug) reports from people building NeoGo source code on these platforms, but so far I've not seen any. Then if there is at least some minimal interest to particular OS/ARCH combination and it doesn't break immediately we can add test/build for this platform to the pipeline (but probably with some "best effort" support class again).

**Comment by gsmachado** [comment]
@roman-khimov so, in summary, what you're asking is: "please, try to build our source in all these platforms, extensive use it, and if there's a bug, report to us"

Is that right?

If so, then I could simply do all the work by myself -- because that's exactly what this issue is about: building the sources targeting these different platforms, and *not* about if the binaries properly work.

**Comment by gsmachado** [comment]
> Then if there is at least some minimal interest to particular OS/ARCH combination and it doesn't break immediately we can add test/build for this platform to the pipeline (but probably with some "best effort" support class again).

I think MacOS would be the first to target and publish with the releases.

**Comment by roman-khimov** [comment]
It's about setting right expectations mostly. When I'm publishing `neo-go-linux-amd64` binary I know it works because I can run it locally, if it doesn't that's my fault and I'll be fixing it. If I'm to publish `neo-go-darwin-amd64` or `neo-go-windows-amd64` I have no idea what's inside and I'm not able to check it. But people will download and run it with expectation that they get something that works. And it'll break. And they'll submit bug reports (or just blame these NeoGo folks that can't create proper node). And I wouldn't be able to test their reports (I can help with some theories, but no more than that).

Of course if our test suite passes on this OS/ARCH combination then we have at least some chance that the resulting binary doesn't eat kittens on breakfast, but still there is this issue. So if at least anyone could try building/running our node on OS/ARCH they really need and tell us what comes out of it it'd be helpful. And then we could consider adding this combination as at least somewhat supported.

We'd like to have more OS/ARCH combinations available for our users, we even used `neo-go-linux-amd64` (not `neo-go`) name for the binary we publish since the beginning and our release instruction specifically mentions this possibility. But I can't publish random binary that no one knows anything about as official release.

**Comment by gsmachado** [comment]
@roman-khimov: I understand your concerns about delivering things that actually work, and not trash. I agree, 100%.

But, generating binaries (adapting the `Makefile`) doesn't mean we will add those to the releases from one day to the other. What about if this is prioritized and we start from that first?

**Comment by roman-khimov** [comment]
I guess it would be easier to talk about it in a real PR then, because at the moment I'm not sure what you want to change in the `Makefile`. It's supposed to work for native builds on any platform and it doesn't mess with `GOOS` or `GOARCH` by itself, so theoretically you should be able to cross-compile with just `GOOS=X GOARCH=Y make`. But if we can improve something here, I'm all ears.

**Comment by roman-khimov** [comment]
With 0.99.1 the only thing we don't have from the original list is linux-arm, but for some strange reason I don't have any Pi.

**Comment by roman-khimov** [comment]
4/5 is a pretty good ratio to say that it's solved. Any additional platforms can be added if they're tested, but we don't have any specific plans for them at the moment.
