### ISSUE TITLE
Stateroot mismatch at testnet's 180464

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2021]
There is one transaction (0xc88cc78efb1854978d24ddbbfe8dea731141c39e9c735b484cf101ece26203fe) there that works without any issues, but:
```
2021-06-20T17:26:02.356Z        ERROR   can't add SV-signed state root  {"error": "stateroot mismatch at block 180464: abf6b8a1589bda54423a241925df83a157c437a9293d706327c356fca25680b6 vs 96a878d57b98b8eae785d0db987f12727ae1860f402fbeb30237e53551d7988f"}
```

**Comment by fyrchik** [comment]
This is a deploy transaction with `Extra` field in the manifest. We save it unchanged (using `json.RawMessage`), while C# node unmarshals it to object and marshals again _without indentation_ https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Manifest/ContractManifest.cs#L90 .
The problem occurs because `Extra` field of this manifest contains spaces:
```
{
        "Author": "77696c6c",
        "Email": "77696c6c@gmail.com",
        "Description": "Lyrebird USD Token"
    }
```

I will check if this is indeed the case. If so, it is better to fix on C# side in future, but for current release we can try some ad-hoc marshaling scheme, maybe reuse orderded maps from oracle filters.

**Comment by roman-khimov** [comment]
Hi, neo-project/neo#2345.
