### ISSUE TITLE
Go 1.18 generics

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2377]
Looks like generics are still somewhat experimental in 1.18 and support for them will be improved and extended in future versions, so it's likely we'll only use them with 1.19 or later. Still, in this bug we can already collect ideas for their usage.

**Comment by fyrchik** [comment]
1. `util/slice` package is a low hanging fruit.
2. We can get rid of reflection for `GetVarSize` and array marshaling in `io`. I have tried to do it in a single function and it was a mess because of the need to specify 2 types explicitly. However if we split this in 2 functions (one for array of pointers, another for array of raw structs) things may look better.

**Comment by roman-khimov** [comment]
1. Client-side RPC iterators.
2. WSClient subscriptions.

**Comment by roman-khimov** [comment]
Type-specific vm.Stack can be nice too.

**Comment by AnnaShaleva** [comment]
We can also add generic wrappers for event-related methods that can be generated by RPC binding generator (`*EventsFromApplicationLog`, etc), see https://github.com/nspcc-dev/neo-go/pull/3008#discussion_r1202990441.

**Comment by AnnaShaleva** [comment]
https://github.com/nspcc-dev/neo-go/issues/3100 can also be supported using generics.

**Comment by roman-khimov** [comment]
I think this issue no longer makes any sense. We're using generics where needed, we still have some areas where they can improve things, but overall it's not like "bring generics into every package immediately" situation. We'll do them where and when appropriate.
