### ISSUE TITLE
Change fmt.Println to log statements

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#247]
- This should not be done now as the logging component has not been finalised.
- We should also evaluate places where we can remove the, to be log statement altogether

**Comment by volekerb** [comment]
I believe this can be done with changing logging to uber/zap in [284](https://github.com/nspcc-dev/neo-go/issues/284) wdyt?

**Comment by decentralisedkev** [comment]
@volekerb Sounds good. I don't know about logger performance so my input on this topic is insignificant.

The plan was to create a logging interface for each module. Then pass a specific logger to each module. The easier way would be to import `uber/zap` then change all fmt.Println to `zap`.

**Comment by volekerb** [comment]
Yes it could be done this way. I believe this one could be closed once (284)[https://github.com/nspcc-dev/neo-go/issues/284] done

**Comment by roman-khimov** [comment]
I think we should handle this one first and then move on to #284, because here we're talking about messages being spit out without any logging system and these should all be fixed to use one (we're using logrus already, so it's easier to stick with it for now). Internal components should pass errors and they should be logged in some way when and where it's appropriate. So it's not OK for VM to print anything on the screen, but it's OK for a function that tries to add a block to the chain to log an error in a VM that made this attempt unsuccessful.
