### ISSUE TITLE
RC4 testnet chain can't be procesed with 10K MaxTraceableBlocks

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2494]
RC4 testnet configured this way:
```
@@ -1,6 +1,7 @@
 ProtocolConfiguration:
   Magic: 877933390
-  MaxTraceableBlocks: 2102400
+  MaxTraceableBlocks: 10000
+  RemoveUntraceableBlocks: true
   InitialGASSupply: 52000000
   SecondsPerBlock: 15
   MemPoolSize: 50000
```
can't be processed with 0.98.3/4/5:
```
failed to add block 311842: onPersist failed: VM has failed: at instruction 0 (SYSCALL): insufficient funds
```
It can with 100K. Technically, it can be a feature in that there really exists some transaction on the chain that looks into the history of more than 10K blocks ago (in which case it's OK to fail), but it needs to be investigated.

**Comment by fyrchik** [comment]
Related #2188 .

**Comment by roman-khimov** [comment]
Huh. It technically even is the same, but for some reason I wasn't able to reproduce it back then.

**Comment by AnnaShaleva** [comment]
I compared states of two chans, first of them is restored using standard testnet settings, and the second one uses 10K of `MaxTraceableBlocks` and have `RemoveUntraceableBlocks` set to `true`. The first statediff is at the height of 311841 (right before the described issue with 311842 block).

Block 311841 contains a single transaction:
```
{
   "netfee" : "601760",
   "script" : "DAhHQVMtVVNEVAKtawQAEsAfDA9nZXRQcmljZVJlcXVlc3QMFKTc6ve1/NwPJV4ZMyUQFMXPrLsAQWJ9W1I=",
   "signers" : [
      {
         "account" : "0xe01b9fa60ae8ffac8f49fdd9afb1df3beb949c4f",
         "scopes" : "CalledByEntry"
      }
   ],
   "validuntilblock" : 317599,
   "hash" : "0xa8cdfba9f622e6c83857cdaaed749ac84c7eebc72b9ebe01a0fcfe6e53ae7b53",
   "sender" : "NTAv9Q5p9Vsckku56sbWSHQBkg3c5ntBk1",
   "sysfee" : "153897525",
   "nonce" : 577281848,
   "version" : 0,
   "attributes" : [],
   "size" : 220,
   "witnesses" : [
      {
         "verification" : "DCEDDTcKB5V67G1g1ANEyLRsclFy2/9Fqmb13fA81dIoJ8dBVuezJw==",
         "invocation" : "DEAnohDVzppQhOIruQgRILI3pwgpE2DPOVK0bh6leayvRH/4fqN1ukUKHLyPouA8rpEn1SbSsiu+wUjw9/fF3/tP"
      }
   ]
}
```
The transaction script is the following:
```
NEO-GO-VM > loadbase64 DAhHQVMtVVNEVAKtawQAEsAfDA9nZXRQcmljZVJlcXVlc3QMFKTc6ve1/NwPJV4ZMyUQFMXPrLsAQWJ9W1I=
READY: loaded 62 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE       PARAMETER
0        PUSHDATA1    4741532d55534454 ("GAS-USDT")    <<
10       PUSHINT32    289709 (ad6b0400)
15       PUSH2
16       PACK
17       PUSH15
18       PUSHDATA1    676574507269636552657175657374 ("getPriceRequest")
35       PUSHDATA1    a4dceaf7b5fcdc0f255e1933251014c5cfacbb00 // contract https://dora.coz.io/contract/neo3/testnet_rc4/00bbaccfc514102533195e250fdcfcb5f7eadca4
57       SYSCALL      System.Contract.Call (627d5b52)
```

The transaction calls `OKexProvider` contract: https://dora.coz.io/contract/neo3/testnet_rc4/00bbaccfc514102533195e250fdcfcb5f7eadca4. The source code of the contract can be found [here](https://github.com/bettybao1209/PriceFeedsService/blob/master/OKexProvider.cs).

The contract uses [Ladger's `getBlock` call](https://github.com/bettybao1209/PriceFeedsService/blob/5748210647009380039ebe77db6fd2cca8af1d4a/OKexProvider.cs#L29). The contract asks for a block 289709 while the current height is 22132 blocks higher, so the requested block is untraceable => the transaction FAULTed on the modified chain setup right before the request to native Oracle contract.

The next block contains the Oracle response which fails because there's no request has been sent (and paid) (the previous transaction is FAULTed):
```
   "signers" : [
      {
         "scopes" : "None",
         "account" : "0xfe924b7cfe89ddd271abaf7210a80a7e11178758"
      },
      {
         "account" : "0x6bd13788efe92d9d29cd123354ac5218be0e45e0",
         "scopes" : "None"
      }
   ],
   "attributes" : [
      {
         "result" : "W10=",
         "type" : "OracleResponse",
         "id" : 96,
         "code" : "Success"
      }
   ],
   "validuntilblock" : 317601,
   "version" : 0,
   "sysfee" : "97306515",
   "script" : "wh8MBmZpbmlzaAwUWIcXEX4KqBByr6tx0t2J/nxLkv5BYn1bUg==",
   "nonce" : 96,
   "hash" : "0xe440b010add3720a6e7617661c07c9f835149bf3d6e514efe847c442947bd2ba",
   "witnesses" : [
      {
         "invocation" : "",
         "verification" : ""
      },
      {
         "verification" : "EwwhAxIGEatCablL0HmCw3Tf44iNi9NrAImkLK/q5lK1U27qDCECIL4gt/3gW/1dmCxCCgRGPdExb/FPDrr2Wz2e8ns4uikMIQObRQQMxSmWYWXvXf89BGpJYFIM5hauFw4mXWaeDi3n9AwhAq9Xd3UQHZx1sw0p1W3gNuJjiMrF5JCVvt1QPEuCEyDaFEGe0Nw6",
         "invocation" : "DEAIkBLMBta9+f1f4vbrQeEigFRzCcCA8+4IxhTOhThoWZ130ANrq6QUQF+gQDqUSNYQHt+kIbEbdMWpvjxspz9IDEB+WRcPRASJp7N1VrBv0gpQG8Xm//o1Y9aXGulXmzqV0LRK9CW8LBD5A5dOx1WUjxTjnhRLz3X7tbtYiPVLCF7JDEAasdwcGR9O/k+IIxzuUS7Gwojg4IRGe/Mtg+lTBf7InbEwFCBNj+ilx2qSVvwPyZ2Zhtiugifez0+tPyse89q5"
      }
   ],
   "netfee" : "2693485",
   "size" : 470,
   "sender" : "NTz4UrybSL4C7HSfaVpXV6hcsWTkks8Nrj"
}
```

The Oracle response script:
```
NEO-GO-VM > loadbase64 wh8MBmZpbmlzaAwUWIcXEX4KqBByr6tx0t2J/nxLkv5BYn1bUg==
READY: loaded 37 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE       PARAMETER
0        NEWARRAY0        <<
1        PUSH15       
2        PUSHDATA1    66696e697368 ("finish")
10       PUSHDATA1    588717117e0aa81072afab71d2dd89fe7c4b92fe
32       SYSCALL      System.Contract.Call (627d5b52)
```

**Comment by AnnaShaleva** [comment]
> Technically, it can be a feature in that there really exists some transaction on the chain that looks into the history of more than 10K blocks ago (in which case it's OK to fail)

So it's true, the described behaviour is not a bug, it's a consequence of `MaxTraceabeBlocks` change.

> but for some reason I wasn't able to reproduce it back then.

But it should be reproducable anyway, are you sure that you've used proper settings while trying to reproduce it?

**Comment by roman-khimov** [comment]
OK, so it's not a bug, it's just that testnet can't be processed with this MTB setting.
