### ISSUE TITLE
dBFT liveness lock

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2552]
See neo-project/neo#2029 comments, we still have this problem.

**Comment by roman-khimov** [comment]
There are some interesting models in https://github.com/nspcc-dev/dbft/pull/69, but there is a contradiction between dBFT goals and liveness, models solving this problem have other problems. WONTFIX here.

**Comment by AnnaShaleva** [comment]
Faced on NeoFS mainnet on NeoGo v0.119.0 one more time. Restart of CNs one-by-one don't help this time (likely, due to https://github.com/nspcc-dev/neo-go/pull/4240): nodes restart with the same behaviour as before restart. moros[5-7] changed view to 1, moros[1-4] committed at view 0.

[moros7.txt](https://github.com/user-attachments/files/28633123/moros7.txt)
[moros6.txt](https://github.com/user-attachments/files/28633126/moros6.txt)
[moros5.txt](https://github.com/user-attachments/files/28633122/moros5.txt)
[moros4.txt](https://github.com/user-attachments/files/28633127/moros4.txt)
[moros3.txt](https://github.com/user-attachments/files/28633125/moros3.txt)
[moros2.txt](https://github.com/user-attachments/files/28633121/moros2.txt)
[moros1.txt](https://github.com/user-attachments/files/28633124/moros1.txt)

**Comment by AnnaShaleva** [comment]
Faced on NeoFS mainnet on NeoGo v0.120.0 one more time. Fixed by simultaneous restart of all nodes in the network (including non-consensus nodes). To me it looks like the problem is triggered by cross-nodes inconsistencies in the notary pools causing inconsistencies in the standard node memory pools (the problem appears after notary pool overflow under spikes in the network load). Memory pool inconsistency, in turn, leads to CV because of TxNotFound (some of the nodes contain a transaction, the rest of the nodes did not yet receive it).
[moros7.txt](https://github.com/user-attachments/files/29286227/moros7.txt)
[moros6.txt](https://github.com/user-attachments/files/29286225/moros6.txt)
[moros5.txt](https://github.com/user-attachments/files/29286228/moros5.txt)
[moros4.txt](https://github.com/user-attachments/files/29286223/moros4.txt)
[moros3.txt](https://github.com/user-attachments/files/29286226/moros3.txt)
[moros2.txt](https://github.com/user-attachments/files/29286222/moros2.txt)
[moros1.txt](https://github.com/user-attachments/files/29286224/moros1.txt)
