### ISSUE TITLE
Support multiple listen addresses in network and RPC servers

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neo-go#2780]
It would be nice to bind to multiple IPs simultaneously.
`0.0.0.0` binds to all available addresses which is not what we want in case there are 2 private (P2P) and 2 public IPs (RPC).

**Comment by roman-khimov** [comment]
It's not that trivial for us, we've got:
 * Pprof and Prometheus with Address/Port
 * RPC with Address/Port _and_ TLS section inside with Address/Port
 * P2P with Address/NodePort/AnnouncedNodePort

Different addresses may mean different ports, so technically we need a set of address/port pairs for each of the services. Or a set of address strings (like the ones accepted by `net.Listen()`). There is a compatibility question, but it's relatively easy to keep both settings for a while.

The biggest question though is with P2P and `AnnouncedNodePort`. We use address/port data during the handshake (`version`) and then to connect to other peers/tell them about peers of our own (`getaddr/addr`). We kinda can make `version` message be connection-dependent, but I don't know what are we going to do with `addr` data. A set of pools can be created, but this goes against the idea of P2P network to me and it won't be trivial, filtering from a single pool is not an option either. So my question would be "do we need this at all for P2P?" How this network is supposed to work?

**Comment by roman-khimov** [comment]
For regular services (PProf/Prometheus/RPC) we want to add an `Addresses` configuration option with a list of `address:port` strings (that `net.Listen` can digest directly). That's relatively easy, the only thing is compatibility with the old config, it must be supported and it should be added to the list if used (not worth adding a conflict IMO). It'd be nice to have more unification between `BasicService` and `RPC` as well, since these configurations are the same there.

P2P is a little harder, `Addresses` is also relevant there, but we need to have something for `AnnouncedNodePort` that is not used often, but still is a valid configuration option. What's proposed here is to extend the syntax to be `ip:port[:announcedPort]`, that is if there is an additional port specified it's used as an announced one. I think it'd be easier than using a list of structures, especially considering the frequency of `AnnouncedNodePort` use. What I also want to do along with this change is add a `P2P` section to `ApplicationConfig` and move all other P2P options there, starting with this new one.

The implementation is straightforward for regular services and requires some special attention for P2P. Here we'll have to prepare connection-specific `Version` message now that will use announced port for a particular IP (derived from the connection.

Address pools/discovery logic remains unchanged, we consider users to be responsible in this case and use this option only when both networks are actually connected and true P2P connections possible between nodes from different networks.

Address/Port and NodePort/AnnouncedNodePort should be declared as deprecated (to be removed in around half a year). Same thing for options moved to P2P. All configurations should be updated to use new options.
