### ISSUE TITLE
Null handling in unwrap library

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2795]
> Another issue I'm thinking about is that `array of something` can be naturally substituted by `Null` stackitem and our unwrappers won't accept it. Maybe it's worth to add `Null` support to `unwrap` package for arrays?

> _Originally posted by @AnnaShaleva in https://github.com/nspcc-dev/neo-go/pull/2792#pullrequestreview-1178887775_

It's true that we can have Null in many cases. We can have `nil` in Go at the same time. Maybe it's OK to return it.

**Comment by AnnaShaleva** [comment]
Ping to this issue, because NNS wrapper (#3291) uses `getRecord` NNS method that returns `Null` stackitem in case of missing record of the specified type. And neither `unwrap.UTF8String` nor `unwrap.Bytes` can handle `Null` stackitem. As a result in the described case we've got an error from the NNS wrapper side on attempt to unwrap `Null` into Go's `string` while NNS itself doesn't return any error.

IMO, this behaviour of NNS wrapper is not correct and it will be fixed by this issue. We likely should return an empty string and no error form NNS wrapper in the described case.

@roman-khimov, what do you think?

@AliceInHunterland, this issue is related to error returned from `recordData, err := nnsReader.GetRecord(domainName, recordType)`

**Comment by AnnaShaleva** [comment]
I'd propose to include this issue in 0.106.0 milestone.

**Comment by AnnaShaleva** [comment]
> The problem is, it's not nil. And you can't differentiate NULL and real empty string in this case.

You're right. Then maybe we need to change the NNS wraper itself to return `(*string, error)`? It doesn't look good to me either, but returning an error also seems not very correct to me.

**Comment by roman-khimov** [comment]
It's one of:
 * special method with special behavior (additional API to choose from)
 * special error (keeping the API as is)
 * `*string` (changing the API)

None of them is perfect. But which one to choose depends on typical usage patterns.

**Comment by roman-khimov** [comment]
Voting for a special `ErrNull` here:
 * compatible with the current behavior
 * works for all types in the same way
 * whether Null is a problem or not is entirely contract-specific and depends on what contract returns
 * in case contract never returns Null it's not a problem already and current behavior is more defensive
 * in case contract returns Null it'd require additional handling, but mostly it'd be `if err != nil && !errors.Is(err, unwrap.ErrNull)`
 * returning `nil, nil` is not common in general
 * handling `nil, nil` is easy for slices of strings and similar things where you iterate over the resulting list, but not so for `*string` and alike, it'd require about the same amount of code as the snippet above for `ErrNull` or more

Other opinions and suggestions are welcome.
