### ISSUE TITLE
Store network magic in the DB's Version

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2847]
#### Problem

Currently the following sequence of steps is considered as valid:

1. Start network(e.g. our privnet) with a magic X
2. Wait until several blocks are accepted
3. Stop all the nodes
4. *Change the network magic from X to Y* in the config
5. Start the network again *with the old DB*
6. Wait until some more blocks will be accepted
7. Profit, you have a broken chain. One part of it is signed using X magic, and another one with Y.

It's *very unlikely* to happen on some public network, but on private installations this leads to misunderstanding and can break the chain with some important data.

#### Suggestion

It's clear that the chain wasn't configured properly, so it's not a software bug. But I suggest to include the magic into `Version` structure and forbid to run the node with changed `Version`'s magic. We already have this check, so extending it will save us (and our users) from such bugs:
https://github.com/nspcc-dev/neo-go/blob/3e714a348e704c994588d667a69b4356fab253d9/pkg/core/blockchain.go#L399-L417

Thanks to @carpawell for the case.

@roman-khimov, what do you think?

**Comment by roman-khimov** [comment]
> Wait until some more blocks will be accepted

This can only happen if you do that on or with CNs at the same time. Otherwise they can't pass previous header check.

At the same time, this totally makes sense because it makes the node fail fast (and completely) in this case, it's just a better behaviour for ops.

The only problem is that this will require a change to the DB scheme and a resync, so we can schedule it for 0.101.0, but probably not earlier than that.
