### ISSUE TITLE
Panic occurs with invalid flag passed to neo-go

### ISSUE THREAD

**Issue by vkarak1** [nspcc-dev/neo-go#2886]
Could you please consider is that expected to get panic when wrong flag is passed to `neo-go`?

## Current Behavior
```
root@NB-2140-wsl:~# neo-go -d
Incorrect Usage. flag provided but not defined: -d

NAME:
   neo-go - Official Go client for Neo

USAGE:
   neo-go [global options] command [command options] [arguments...]

VERSION:
   0.99.6-pre-3-gbb756c8d

COMMANDS:
   node      start a NEO node
   db        database manipulations
   contract  compile - debug - deploy smart contracts
   wallet    create, open and manage a NEO wallet
   vm        start the virtual machine
   util      Various helper commands
   query     Query data from RPC node
   help, h   Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
panic: flag provided but not defined: -d

goroutine 1 [running]:
main.main()
        ./main.go:13 +0x4d

```

**Comment by roman-khimov** [comment]
That's the way it is now and it's been like that since f000b7687917f13442e7d2fe471fbcb4b6249547. On one hand, it's OK, since we handle the error and exit (with some error code returned). And it does so for any error, not just wrong flags, probably there are also more places like this in the CLI (except this error handler). On the other, maybe it's a bit too much for errors like this.

Not something that I'd change right now.

**Comment by 532910** [comment]
This is NOK on both hands.
