### ISSUE TITLE
Try using org-specific GH runner for NeoGo builds/tests

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2943]
Once we have it (@aprasolova), we can try using it.

**Comment by AnnaShaleva** [comment]
The performance results for the following set of jobs are taken from the `master` branch for GH runner (Ubuntu 20.04, x64) and from the `sh-runner` branch (`master` + b6596e99a31dd732dec72c088f04f47c50764d6a) for the self-hosted runner (Debian GNU/Linux 11 (bullseye) x64). Three runs were taken for each runner.

```
		Lint	CheckDeps	CodeQL	Coverage	RunTests18		RunTests19
GH		**		**			**		**			11m23s			9m18s
GH2		39s		5s			5m46s	6m8s		12m44s			9m16s
GH3		48s		6s			5m24s	6m1s		14m56s 			9m8s
-----------------------------------------------------------------------------
SH		1m38s	10s			**		2m31s		**				5m25s
SH2		1m22s	7s			2m50s*	2m8s		6m11s			1m9s (cache?)
SH3		1m19s	6s			2m29s*	2m24s		1m26s (cache?)	1m10s

* - plus one more additional step in the job for self-hosted runner (setup go for correct codeql autobuild).
** - workflow was manually cancelled for further improvements, thus results are incomplete for this run.
```

Based on the table above, I'd suggest keeping GH runners for `Lint` and `Check internal dependencies` jobs and using four (4) self-hosted Linux-based x64 runners for `CodeQL`, `Coverage`, `RunTests18` and `RunTest19` jobs. It should be noted that GitHub only assigns one job to a runner, thus I'd suggest using four self-hosted runners instead of a single instance. I'd expect all our Linux-based jobs to finish within 5-6 minutes (in the worst case) and 2-3 minutes (in the best case), which is extremely nice.

It should be noted that we still have to keep GH runners for macOS- and Windows-based tests. It still takes ~8-10 minutes to finish the macOS-based test job and ~28-35 minutes to finish the Windows-based test job.

When it comes to building jobs, I'd suggest continuing to use GH runners for them, as far as there are not a lot of them (two, in fact: build CLI and build Docker image) and these runners are Ubuntu-based which might be better in some way (I'm not sure whether it's important). @roman-khimov, what do you think about building jobs?

**Comment by AnnaShaleva** [comment]
> GitHub only assigns one job to a runner

Another important note connected with it is that, given four self-hosted runners per our repo, there can be only four concurrently running jobs. In case of two PRs opened at the same time, the second of them will have to wait until the first one ends his testing jobs.

**Comment by roman-khimov** [comment]
> It should be noted that we still have to keep GH runners for macOS- and Windows-based tests.

Which means that we still have to wait for the same amount of time to get complete test results. Which in turn means that we don't gain a lot from this change wrt NeoGo. Plus the concurrency issue. If GH would use the runner _in addition_ to the ones it has, that'd be different.

Let's leave it as is for NeoGo, NeoFS is different in that it doesn't have that big number of platforms and that its tests are very resource and time consuming.

**Comment by AnnaShaleva** [comment]
> Plus the concurrency issue.

This one has a solution, we can use an auto-scaling (https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#about-autoscaling). Each time a new job is queued the new runner should be created for it by autoscaling tool. After the job is completed the runner is supposed to be dropped.

> we still have to wait for the same amount of time to get complete test results

The point is that we need Windows-based machine to properly run self-hosted runner on it for Windows tests.

> If GH would use the runner in addition to the ones it has

It's impossible, for a single job you can either use the GH runners or use a group of self-hosted ones.

Don't you consider the idea of setting up a Windows machine in our office?

**Comment by AnnaShaleva** [comment]
> we don't gain a lot from this change wrt NeoGo

With this change, we get the results of the linux-based tests faster :) It can be useful when you can't run the tests on your local machine, although I always do it before the PR creation. Indeed, this improvement would be very useful for Windows-based tests, because I don't always have my Windows machine with me.

**Comment by roman-khimov** [comment]
> Windows machine in our office?

Tell @532910 and @aprasolova about it, they'd be happy to hear that. Most likely it'd be too painful to maintain. At least until we have more use casese for this platform.

**Comment by AnnaShaleva** [comment]
OK, let's postpone this until we have the proper hardware.
