### ISSUE TITLE
Fix Lint job issues

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2948]
The linter probably has got the subsequent update, we need to fix all the warnings found. See the Lint job comments to #2947.

**Comment by ZhangTao1596** [comment]
I already have one https://github.com/ZhangTao1596/neo-go/tree/fix-format. I will create a pr after a second check.

**Comment by ZhangTao1596** [comment]
![image](https://user-images.githubusercontent.com/22324403/227451155-f2bacac4-23cb-40b9-b30f-9801ad279968.png)

About 177 `unused-parameter` error. Should we disable this check or correct them?

**Comment by roman-khimov** [comment]
It's case-by-case, `empty-block` should be easy enough to go through and fix/comment out depending on particular situation. `doc_test.go` is code samples used in package documentation, they're important, but at the same time they're not a real code, just some illustration (that has to compile correctly though).

`unused-parameter` is more tricky. We have a lot of cases where it's intentional, yet at the same time there might be a number of cases where we can improve our code. I'd suppress this check for now and create a separate issue to deal with it, this will just take some time.

We at the same time should get to green lint status soon, otherwise we'll get used to ignoring it.
