### ISSUE TITLE
Notary subsystem setup in distributed environment

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2964]
We love using the notary subsystem in various installations. But it needs a role designation for a fresh network. But the role management contract requires committee multisignature to perform any actions. But we don't have any notary nodes designated yet. That's what easily happens in nspcc-dev/neofs-node#2195 during initial setup phase.

Our possibilities:
 1. Allow to set notaries using just a single committee member. Breaks role management and the committee concept, not an option.
 2. Treat committee members as notaries implicitly. Seems to be too magic and differs a lot from other roles. Breaks some economics assumptions as well.
 3. Use a predefined (preconfigured) list of notary nodes to be used during notary contract setup. Or just a simple `EnableCommitteeNotary` knob to include committee members there in block 0. Pretty clean and easy (and what we're going to use in NeoFS 99.9% of the time), but can differ a bit from the C# implementation (unless we're to make it a part of the standard protocol) and looks somewhat strange (we don't have predefined oracles, for example).
 4. Create a chain dump along with new keys in `neofs-adm morph generate-alphabet` and add it into some kind of config as well. Conceptually cleaner (we get a standard role designation transaction in the end), but additional files is what we're trying to avoid and in some cases it might be useful to generate keys independently.
 5. Allow notary service to work on a node without being designated. Breaks the economics somewhat, but it boils down to some minimal `PostPersist` (don't distribute the fee if there are no nodes) and `verify` (allow to pass if there are no nodes) changes in the notary contract. This might be a little dangerous in its `verify` part, but it at the same time can be a part of the regular protocol.
 6. Collect committee signatures in some other way via extensible payloads. Requires a whole new protocol, even though technically committee members can use it.

Opinions, preferences, other options? @cthulhu-rider, @AnnaShaleva? 3 and 5 seem to be viable to me.

**Comment by cthulhu-rider** [comment]
I am poorly familiar with the governance and notary mechanisms. Anyway, here's a quick option.

On a cold start of the application, the chain starts with a random single-node committee. Per initial block (ideally) node:
* assigns roles of notaries to nodes configured as a committee in the usual sense of the word
* on his own behalf transfers the management of the committee to these nodes

In words, everything should work out of the box without changes and extensions (is it?).

As a small disadvantage in excessive centralization. However, at a cold start, it is much less critical and is quite understandable in practice. On the one hand, the nodes need to be synchronously configured anyway in order for the chain to start running at all. On the other hand, the failure of any of the nodes at the start (even within the consensus threshold) is much more critical than later.

P.S. it appears that this option is offered with native support by option 3 which LGTM.

**Comment by roman-khimov** [comment]
That's ValidatorsHistory/CommitteeHistory reuse in its essence. Theoretically possible and can be done with zero NeoGo changes. But it complicates configuration somewhat and requires some additional care.

**Comment by roman-khimov** [comment]
Option №8: use NNS. `notaryXX.bootstrap` can hold a signature for committee-signed transaction in a TXT record.

**Comment by AnnaShaleva** [comment]
1 is not an option to me, it's just dangerous.

2 may be applicable to neofs, but how about other chains? And I'd say it's not the kind of expected behaviour if we're comparing Notary with Oracle nodes. Notaries is a separate role that doesn't connected with committee, so I don't like this option.

3 seems to be valid, but we need to have predefined Notary nodes set in RoleManagement contract as far (so that everything works properly). This assumes allowing some non-empty initial state for node roles inside the RoleManagement, and it seems to me that it's not exactly the way how this contract should work.

4 is the option I like the most (in general). We do properly collect signatures via some other way of communication, it's not required to have chain dump, we may think about some other way of communication, e.g. to perform it on-the-fly or via the some additional contract that could collect signatures for us to designate new notary node. But the chain dump seems to be the easiest way. And in some real network where there's the same problem with Notary nodes designation, the half-signed transaction is likely to be passed via some discord channel manually. Thus, option 4 seems to be more "native" to me, it's just the way how the first designation is supposed to work (and it's just a single designation transaction that is collected by this cludgy way *per the whole chain lifetime*, so I think that we can allow to do it once).

5 breaks the economy model. Here we do allow some random node to handle notary requests and these requests will be accepted. This random node isn't chosen by committee, couldn't it can be dangerous in some way? I don't like changes inside the Notary verification scheme, it's just not the reason why we must break the Notary contract.

6 is the option that is very similar to 4, we just trying to thinking some other way the committee nodes can communicate with each other to collect the signatures. But I don't think that the first notary nodes designation worths protocol extension. Because this protocol extension will be used only once to designate new Notary node, and after that the Notary subsistem can be used for the same purposes. In other words, once the Notary node is designated, the protocol extension becomes useless. Not worth the effort, IMHO.

8 looks good to me, don't see disadvantages.

To summarize, I'd pick option 8 or 4. They don't require much effort, they don't break the exising protocol, they don't add new cludges to the existing system. But if these two are not an option, then I'd better pick the option 3 and add some default set of notary nodes inside the RoleManagement. It works much cleaner and natively than other scenarios except 8 and 4. If we can't allow 8 or 4, then we can make an exception for the Notary service, because it's kind of special and the whole on-chain multisignature process isn't allowed without it. Thus we may treat pre-defined Notary nodes as a network (and RoleManagement's) setting. But in this case we have to make some changes inside the RoleManagement contract and perform checks that this config value doesn't being changed after node restart.

**Comment by roman-khimov** [comment]
@cthulhu-rider, how about 8? It certainly complicates setup logic with all of the NNS dances, but we have some already, so it's just a bit more of them.

**Comment by cthulhu-rider** [comment]
@roman-khimov now we are already playing games with NNS, so I think that's definitely not a bad idea.

But I didn't catch exactly what's the exact idea tbh. We deploy NNS w/o notary then, right?

**Comment by roman-khimov** [comment]
We have to do it anyway and it can be done. The first node deploys it, then everyone pushes signatures to some predefined domains to create committee-signed transaction enabling the notary. Then we're golden.

**Comment by roman-khimov** [comment]
NeoFS IR is the only of its kind, other app deployed to mainnet/testnet will just get an already running service (like they have oracles now, for example).

**Comment by roman-khimov** [comment]
OK, then it can be solved on the app side.
