### ISSUE TITLE
notary: When deposit parameter `till` defaults?

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#2986]
[docs](https://github.com/nspcc-dev/neo-go/blob/master/docs/notary.md) say that `till` prm

> Default till value is the current chain height + 5760.

i tried to make deposit with zero `till` and got `till shouldn't be less then the chain's height` panic.

i've found this place of code where panic occurs, it prevents prm defaulting, isn't it?
https://github.com/nspcc-dev/neo-go/blob/f0a5430b5b42440ffc09e06a4505de714e366650/pkg/core/native/notary.go#L235-L237

i've also caught place where value is reset. According to this, `till` defaults on first self-deposit 
https://github.com/nspcc-dev/neo-go/blob/f0a5430b5b42440ffc09e06a4505de714e366650/pkg/core/native/notary.go#L249-L251

Please review code/docs and clarify default `till` behavior

**Comment by roman-khimov** [comment]
I'd keep the behavior as is and fix the documentation. Rationale: if you're the owner, you're responsible for your `till` value. When there is some `data`, it inevitably has both the `to` address and `till`. Address can be `nil`, `till` can't, so set some value you want.

The other option (or extention maybe) though is using this default `if args[2] == nil`, so if one doesn't set any `data` at all (and we just error out in this case now) then we can assume `to == nil` and this default `till` value, we have nothing else anyway. But this is an incompatible change and I'm not sure we don't have any transactions transferring GAS with `data == nil`, it might require some attention/hardfork.

@AnnaShaleva?

**Comment by AnnaShaleva** [comment]
The code works properly, as Roman said, it's prohibited to set `Till` if you're not the deposit owner. And if you're the owner, then you must set some *valid* value. I'll update the documentation, it's probably not as clear as expected.

> The other option...

I'd prefer to keep the code as is because the owner should be aware of the exact value when deposit is unlocked. And if it's not set, then it's better to let the user know that something is wrong with the deposit. Although if there's a strong demand to set the default `till` value, then I'd prefer to still treat `args[2] == nil` case as an error and allow to set `args[2][1]` (i.e. `till`) to `stackitem.Null` value like it is done with `args[2][0]` (`to`) value.
