### ISSUE TITLE
Decouple actor from implementation of transaction signer

### ISSUE THREAD

**Issue by stevvns** [nspcc-dev/neo-go#3015]
Current implementation of rpc client's [actor](https://github.com/nspcc-dev/neo-go/blob/abf3ef5af73c85267714d7cc1118a33a4475bd20/pkg/rpcclient/actor/actor.go) has direct dependency on struct [transaction.Signer](https://github.com/nspcc-dev/neo-go/blob/abf3ef5af73c85267714d7cc1118a33a4475bd20/pkg/core/transaction/signer.go#L15). Actor implements logic to sign transactions and generate witnesses based on contract's attributes in `transaction.Signer`.

This covers basic scenarios when signers are wallets or proxy contracts without parameters. However, if we need a more complex scenario that requires us to pass extra parameters to proxy contract (that is, to Verify method of proxy contract) we are required to build transaction from scratch similarly to what neofs-node does in notary for [signers](https://github.com/nspcc-dev/neofs-node/blob/9831353981ebfa8d543ef27a56577a08bcd954a5/pkg/morph/client/notary.go#L553) and [witnesses](https://github.com/nspcc-dev/neofs-node/blob/9831353981ebfa8d543ef27a56577a08bcd954a5/pkg/morph/client/notary.go#L623). 

We have to build transaction ourselves, because we need to build scripts for witness that includes parameters for `Verify` method call. Current implementation of actor does not allow us to inject such logic in the transaction processing flow. However, it would be much more convenient if we could control behavior of signers and logic of witnesses outside actor.

So, the proposal is:

Step 1. In [actor](https://github.com/nspcc-dev/neo-go/blob/master/pkg/rpcclient/actor/actor.go) replace struct [SignerAccount](https://github.com/nspcc-dev/neo-go/blob/abf3ef5af73c85267714d7cc1118a33a4475bd20/pkg/rpcclient/actor/actor.go#L43) with an interface that goes something like this:
```go
type Signer interface {
	SignTx(net netmode.Magic, tx *transaction.Transaction) error
	TxSigner() transaction.Signer
	TxWitness() transaction.Witness
}
```

Step 2. Provide implementations of the interface `Signer` for wallet and contract, something like:
```go
type WalletSigner struct {
	Account *wallet.Account
	Scopes  transaction.WitnessScope // and AllowedContracts,AllowedGroups,Rules
}

func (s *WalletSigner) SignTx(net netmode.Magic, tx *transaction.Transaction) error {
	return s.Account.SignTx(net, tx)
}

func (s *WalletSigner) TxSigner() transaction.Signer {
	return transaction.Signer{
		Account: s.Account.Contract.ScriptHash(),
		Scopes:  s.Scopes,
	}
}

func (s *WalletSigner) TxWitness(tx *transaction.Transaction) transaction.Witness {
	return transaction.Witness{
		VerificationScript: s.Account.Contract.Script,
	}
}

type ContractSigner struct {
	Hash   util.Uint160
	Scopes transaction.WitnessScope `json:"scopes"`
}

func (s *ContractSigner) SignTx(net netmode.Magic, tx *transaction.Transaction) error {
	// Ideally we want FakeContractAccount and others to be encapsulated in these ready-to-use signers
	account := wallet.Account{
		Address:  address.Uint160ToString(s.Hash),
		Contract: &wallet.Contract{Deployed: true},
	}
	return account.SignTx(net, tx)
}

func (s *ContractSigner) TxSigner() transaction.Signer {
	return transaction.Signer{
		Account: s.Hash,
		Scopes:  s.Scopes,
	}
}

func (s *ContractSigner) TxWitness(tx *transaction.Transaction) transaction.Witness {
	return transaction.Witness{
		// Here we can have some convenience logic to convert parameters (if any) into byte-code...
		// Parameter values can be stored in instance of ContractSigner
	}
}
```

Step 3. Remove logic that produces scripts and witnesses in actor itself. Instead, call signer interface methods.

**Comment by roman-khimov** [comment]
I don't think `transaction.Signer` is a problem, you have to have this data anyway to build a transaction, it's basically copy-pasted into it and to have all the features transaction signers have it has to be a complete `transaction.Signer`. The problem is more in `*wallet.Account`. It already can have [arbitrary contracts](https://pkg.go.dev/github.com/nspcc-dev/neo-go/pkg/wallet#Contract) inside and they can deployed and they can have any parameters at the same time. So primitive cases like zero parameters are even already handled by the `SignTx` method:
https://github.com/nspcc-dev/neo-go/blob/7306beca4ddc013157027ca0de35686c2dd0c538/pkg/wallet/account.go#L111-L113
But most likely you've already seen that.

I'd say this should be solved either by replacing the `Account` part of `SignerAccount` by some interface or expansion of `wallet.Account` to handle more complex scenarios. But the problem itself is very much valid and in some ways already known, it's just that we hadn't had any practical scenarios like that before, even though Notary contract takes a signature in its `verify`:
https://github.com/nspcc-dev/neo-go/blob/abf3ef5af73c85267714d7cc1118a33a4475bd20/pkg/core/native/notary.go#L361-L365

**Comment by stevvns** [comment]
I totally concur that interface in place of `*wallet.Account` would provide sufficient flexibility to address the issue. Thank you, @roman-khimov!
