### ISSUE TITLE
Upgrade CLI library

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#3097]
Looks like we're a bit outdated with 1.22.5: https://cli.urfave.org/migrate-v1-to-v2/

Related to #2628, #2861, #2886.

**Comment by roman-khimov** [comment]
Migration to Cobra can also be considered, but needs some justification (nspcc-dev/neofs-node#2525 has a bit of it).

**Comment by AnnaShaleva** [comment]
Within the scope of this issue we should also apply `Required` flags functionality where needed and functionality that allows to require one flag from a set of flags. See https://github.com/nspcc-dev/neo-go/pull/3278#issuecomment-1869444068 for details.

**Comment by AnnaShaleva** [comment]
The following new features may be useful for us: https://cli.urfave.org/v2/examples/flags/#grouping, https://cli.urfave.org/v2/examples/flags/#placeholder-values.

For required flags (#2861) we need to combine https://cli.urfave.org/v2/examples/flags/#required-flags with https://cli.urfave.org/v2/examples/flags/#flag-actions to validate the flag is not empty.

**Comment by AnnaShaleva** [comment]
Just for the record: migration to Cobra has been declined in favor of Urfave upgrade since there's no issues that can't be resolved with Urfave. The issue with UTF-8 compatibility I was thinking about (https://github.com/nspcc-dev/neo-go/issues/1743) was fixed in VM CLI by replacing Abiosoft with Urfave CLI, so it's not a problem for Urfave CLI.
