### ISSUE TITLE
Develop Encoding/Decoding library

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#491]
Issue:
While writing code we have to encode/decode our bytes/structures in a particular way. But all the code we write for it looks more or less like copy paste and it's very hard to check all the pieces and that we didn't make any mistake there. 
So I believe there are different tools which can solve that problem and we can save time/money.
Let's say protobuf/thrift/smth else can be investigated.

@fyrchik might have some ideas around that

**Comment by fyrchik** [comment]
Write a go backend to http://kaitai.io/ or a custom generator from some declarative description of wire format.

**Comment by roman-khimov** [comment]
>  Let's say protobuf/thrift/smth else can be investigated.

They can't because they use different serialization formats.

We probably can try to develop something like json/yaml packages and use struct tags, but if you look at the `yaml` package, it's on the order of 5K lines of code, so it doesn't seem to be trivial (or a good first issue). Also consider things like abc583385328cf468d4e2933884e03021aca35bf or 8ececdc9a7d6d60fe7f9303d5fba5b4cb8dc3a57, you have to write your own serialization/deserialization for them anyway.

And maybe it's not that big of an issue. We have a limited number of things transmitted over the wire, it doesn't change in a stable version of NEO (you write it once, test it and forget about it) and NEO 3.0 has even less such things now:
```
# NEO 2.0
$ ls -l neo/Network/P2P/Payloads/ | wc -l
38
# NEO 3.0
$ ls -l neo/Network/P2P/Payloads/ | wc -l
25
```

**Comment by volekerb** [comment]
> They can't because they use different serialization formats.
True. It was just an example to illuminate how this problem solved.

> like json/yaml packages and use struct tags
True, it could make life easier not only for us.

> Also consider cases like abc5833 or 8ececdc
True, but that's a corner case. In general I believe it's not required to write decoders/encoders each time by yourself. Even only in case it's super unique decoding=).

> And maybe it's not that big of an issue.
Dunno. I haven't seen any PR without writing/reading bytes codelines.

**Comment by roman-khimov** [comment]
IMO, our wire format processing is already good enough, it's not complicated, not hard to implement and use. What worries me more is our state as we have way more data in state DB than on the wire and we're more dependent on speed of its processing rather than wire structures (blocks and transactions). And here we can make use of encoding/gob, which is a topic of #762.

-ENOBUG here.
