### ISSUE TITLE
Investigate encoding/gob for state data format

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#762]
It should be more efficient in terms of encoding/decoding than our current wire format so for all things where we don't care about following the wire format (like blocks or txes) it makes sense to try to use it and see whether it speeds up block processing for us.

**Comment by fyrchik** [comment]
I have made some benchmarks with `Account` encoding/decoding. Here are the results:
```
BenchmarkAccount_EncodeBinary/EncodeBinary-8         	  157672	      7302 ns/op
BenchmarkAccount_EncodeBinary/gob.Encode-8           	   18856	     62427 ns/op
BenchmarkAccount_EncodeBinary/DecodeBinary-8         	    2166	    525323 ns/op
BenchmarkAccount_EncodeBinary/gob.Decode-8           	   12469	     94163 ns/op
```
`EncodeBinary` is much faster than `gob.Encode`.
`DecodeBinary` is much slower than `gob.Decode`.

Turns out, that most time in `DecodeBinary` is spent on decoding `*keys.PublicKey`. This is because of 2 reasons:
1. When keys are in compressed format, decoding involves calcualtions in `math/big`.
2. `DecodeBinary` checks if resulting point is on curve which also involves calculations in `math/big`.

After 1-2 points are fixed (keys are encoded uncompressed, don't check if point is on curve):
```
BenchmarkAccount_EncodeBinary/EncodeBinary-8         	  164352	      6879 ns/op
BenchmarkAccount_EncodeBinary/gob.Encode-8           	   18612	     61302 ns/op
BenchmarkAccount_EncodeBinary/DecodeBinary-8         	  122767	      9705 ns/op
BenchmarkAccount_EncodeBinary/gob.Decode-8           	   12412	     94337 ns/op
```
As can be seen, `io.Serializable` is faster in both cases.
Benchmark code lies in the branch https://github.com/nspcc-dev/neo-go/tree/feature/gob.

**Comment by fyrchik** [comment]
We can also try something like this https://capnproto.org/

**Comment by roman-khimov** [comment]
OK, bad idea, not worth it. For some reason my view of `encoding/god` was a bit different than what it actually is and how it works (tied to reader/writer).
